language: python
python:
  - "3.7"

install:
  - pip install -r requirements-dev.txt
  - "TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}"
script:
  - coverage run --source=score -m pytest
  - coverage report
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip

after_success:
  - docker build -t sandjaie/imagescore -f ./Dockerfile