language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
- pip install twine==1.12
- python3 setup.py sdist bdist_wheel
script:
- coverage run --source=tests -m pytest
- coverage report
- coverage run --source=score -m pytest
- coverage report

deploy:
  provider: pypi
  user: sandjaie
  password:
    secure: caj3u8vG9nSmhP30DE8hrglR01eoYzk7SSc0EbABQVNY+i8r9QQvpAoWBmb5jy6K8BjkSWoNXiFYKt1cxct881pfSFHI+to8x7Tkacce7PD63Gh708HLmTXCXLqyx3y5gLF4NfRTBlcDpoM3LAv3t2PGWerYHSjq4ebJPQgkSvPVVtLHamnjvDa7MsW6q+LZup+V0RvMWzYTFRmhjZS/VaGGZ9vsI0HlQ3MDnBJVhAm0j7pis1beWZrmKD905/tE3Hu/CAu5TxsVthfGghePohjA12LBANg2Ljd6dytmZfM5kvTIMgm05Z/KS1lEIsTPKnF7QN3STE4oZMv6S1dIxQzHC7EoKN9tE8fG0MRSojquFwjlD+pSk45+xT0k1V2dq1LdPXEusNaI2QG13nLduR4CbpBzee5LEEWUf0nBjyRYMErhv8S25W9zKMfYIX+ge+sXkEcRqof2gAL8oRUzJLfb6Q6/abPcTj7puqkz6K8dlD1VAyV9tgzIrosTjLMB26LVb21+tlzoEXH2dOJuY2r5I4AT1RU+SzpAfbemKm+ZVoeppKLoE6ugIsWnts7uDICh18mV6Oz5zFlYoafyLF61hI7NLBzb3TMNxfyhzA6tcUnQEArmanxdGaAum7T0xXIEEtu/PE51t8ztDvVzxcFXQCJEFJaURgrRBqiXNGU=
  on:
    tags: true
